os: Visual Studio 2017 RC

init:
- ps: >-
    reg ADD "HKLM\Software\Microsoft\StrongName\Verification\*,*" /f

    if ($env:PROCESSOR_ARCHITECTURE -eq "AMD64")

    {
      reg ADD "HKLM\Software\Wow6432Node\Microsoft\StrongName\Verification\*,*" /f
    }

build_script:
  - cmd: taskkill /f /im MSBuild.exe /fi "memusage gt 40" 2>NUL
  - cmd: build.cmd /restore
  - cmd: build.cmd
  - cmd: taskkill /f /im MSBuild.exe /fi "memusage gt 40" 2>NUL

install:
- cmd: git submodule update --init --recursive

# we run the tests ourselves in build.proj for coverage
test: off

# build cache to preserve files/folders between builds
cache:
  - '%LocalAppData%\NuGet\Cache'
  - '%USERPROFILE%\.nuget\packages'

deploy:
  - provider: NuGet
    api_key:
      secure: 6IOnCr0vcNuRan0YWj7JRzsjZINxy7QuKAsg1HvdmYIOvTMV/ZbFyaRbL5X8OOmY
    on:
      # we only deploy to public NuGet gallery when tagging the repo
      appveyor_repo_tag: true

nuget:
  project_feed: true
  disable_publish_on_pr: false
  
artifacts:
  - path: 'out\*.nupkg'
    name: Package
  - path: 'out\*.vsix'
    name: Extension