os: Visual Studio 2017

init:
- ps: >-
    reg ADD "HKLM\Software\Microsoft\StrongName\Verification\*,*" /f

    if ($env:PROCESSOR_ARCHITECTURE -eq "AMD64")

    {
      reg ADD "HKLM\Software\Wow6432Node\Microsoft\StrongName\Verification\*,*" /f
    }

build_script:
  - cmd: echo /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" >> msbuild.rsp
  - cmd: build.cmd /restore
  - cmd: build.cmd /release

install:
- cmd: git submodule update --init --recursive

# we run the tests ourselves in build.proj for coverage
test: off

nuget:
  project_feed: true
  disable_publish_on_pr: false
  
artifacts:
  - path: 'out\*.nupkg'
    name: Package
  - path: 'out\*.vsix'
    name: Extension
  - path: 'msbuild.log'
    name: Log
