os: Visual Studio 2015

init:
- ps: >-
    reg ADD "HKLM\Software\Microsoft\StrongName\Verification\*,*" /f

    if ($env:PROCESSOR_ARCHITECTURE -eq "AMD64")

    {
      reg ADD "HKLM\Software\Wow6432Node\Microsoft\StrongName\Verification\*,*" /f
    }

build_script:
- cmd: build.cmd %BuildArgs%

install:
- cmd: git submodule update --init --recursive

# we run the tests ourselves in build.proj for coverage
test: off

nuget:
  project_feed: true
  disable_publish_on_pr: true
  
artifacts:
  - path: out\*.nupkg
    name: Package
